/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sampjframe;

import com.github.britooo.looca.api.core.Looca;
import com.github.britooo.looca.api.group.discos.DiscoGrupo;
import com.github.britooo.looca.api.group.discos.Volume;
import com.github.britooo.looca.api.group.memoria.Memoria;
import com.github.britooo.looca.api.group.processador.Processador;
import com.mycompany.sampjframe.banco.Componente;
import com.mycompany.sampjframe.banco.ComponenteCrud;
import com.mycompany.sampjframe.banco.Maquina;
import com.mycompany.sampjframe.banco.MaquinaCrud;
import com.mycompany.sampjframe.banco.UsuarioEmpresa;
import com.mycompany.sampjframe.banco.UsuarioEmpresaCrud;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author guira
 */
public class cadastroServer extends javax.swing.JFrame {

    /**
     * Creates new form cadastroServer
     */
    public cadastroServer() {
        initComponents();
    }
    
    Componente compCpu = new Componente();
    Componente compRam = new Componente();
    List <Componente> discos2 = new ArrayList();
    
    Componente compCpuLocal = new Componente();
    Componente compRamLocal = new Componente();
    List <Componente> discosLocal = new ArrayList();
    
    ComponenteCrud componenteCrud = new ComponenteCrud();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCadastrarMaquina = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        tfSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        tfNomeServ = new javax.swing.JTextField();
        loading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(77, 158, 65));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logoredimensionada.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 386, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Cadastro de Máquina");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Email:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Senha:");

        btnCadastrarMaquina.setBackground(new java.awt.Color(77, 158, 65));
        btnCadastrarMaquina.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCadastrarMaquina.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarMaquina.setText("Cadastrar Servidor");
        btnCadastrarMaquina.setBorder(null);
        btnCadastrarMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarMaquinaActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(255, 0, 51));
        btnVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.setBorder(null);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Nome do servidor:");

        loading.setBackground(new java.awt.Color(1, 1, 1));
        loading.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loading)
                .addGap(129, 129, 129))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfNomeServ, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNomeServ, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(loading)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarMaquinaActionPerformed
        loading.setText("Carregando...");
        UsuarioEmpresaCrud usuarioEmpCrud = new UsuarioEmpresaCrud();
        UsuarioEmpresa usuarioEmpresa = new UsuarioEmpresa();
        String email = tfEmail.getText();
        String senha = tfSenha.getText();
        
        usuarioEmpresa = usuarioEmpCrud.validarLogin(email, senha);
        
        
        if(email.equalsIgnoreCase(usuarioEmpresa.getEmailUsuario())){
            Maquina maquina = new Maquina();
            maquina.setFkEmpresa(usuarioEmpresa.getIdEmpresa());
            String nome = tfNomeServ.getText();
            maquina.setNome(nome);
            maquina.gerarSerial();
            
            MaquinaCrud maquinaCrud = new MaquinaCrud();
            
            maquinaCrud.inserir(maquina);
            
            Looca looca = new Looca();
            
            Processador processador = looca.getProcessador();
            
            Memoria memoria = looca.getMemoria();
            Long memoriaTotal = memoria.getTotal();
            Double memoriaTotalDouble = memoriaTotal.doubleValue();
            Double memoriaTotalDoubleCon = memoriaTotalDouble / 1024 / 1024 / 1024;
            Double memoriaTotalRound = Math.round(memoriaTotalDoubleCon * 10.0) / 10.0;
            
            DiscoGrupo grupoDiscos = looca.getGrupoDeDiscos();
            List<Volume> volumes = grupoDiscos.getVolumes();
            
            List <Maquina> ultimaMaquina = new ArrayList();
            ultimaMaquina = maquinaCrud.selectUltimaMaquina();

            for(Maquina retornoMaquina : ultimaMaquina){
                List <Componente> listaComponente;
                
                listaComponente = componenteCrud.listarFkComponenteMaquina(retornoMaquina.getIdMaquina());
                compCpu.setNomeComponente("CPU " + processador.getNome());
                compCpu.setCapacidadeMaxima(null);
                compCpu.setFkMaquina(retornoMaquina.getIdMaquina());
                compCpu.setFkMedida(1);
                compCpu.setFkMetrica(null);

                componenteCrud.inserirComponente(compCpu);

                compRam.setNomeComponente("RAM");
                compRam.setCapacidadeMaxima(memoriaTotalRound);
                compRam.setFkMaquina(retornoMaquina.getIdMaquina());
                compRam.setFkMedida(1);
                compRam.setFkMetrica(null);

                componenteCrud.inserirComponente(compRam);

                for(Volume volume : volumes){
                    Componente disco = new Componente();
                    disco.setNomeComponente("Disco: " + volume.getPontoDeMontagem());
                    Long volumeTotalLong = volume.getTotal();
                    Double volumeTotal = volumeTotalLong.doubleValue();
                    volumeTotal = volumeTotal / 1024 / 1024 / 1024;
                    volumeTotal = Math.round(volumeTotal * 10.0) / 10.0;
                    disco.setCapacidadeMaxima(volumeTotal);
                    disco.setFkMaquina(retornoMaquina.getIdMaquina());
                    disco.setFkMedida(1);
                    disco.setFkMetrica(null);
                    componenteCrud.inserirComponente(disco);

                }
                
                List <Componente> listaCpu = componenteCrud.listarCpuMaquina(retornoMaquina.getIdMaquina());
                List <Componente> listaRam = componenteCrud.listarRamMaquina(retornoMaquina.getIdMaquina());
                List <Componente> listaDisco = componenteCrud.listarDiscosMaquina(retornoMaquina.getIdMaquina());
                
                List <Componente> listaCpuLocal = componenteCrud.listarCpuMaquinaLocal();
                List <Componente> listaRamLocal = componenteCrud.listarRamMaquinaLocal();
                List <Componente> listaDiscoLocal = componenteCrud.listarDiscosMaquinaLocal();

                
                for(Componente cpu : listaCpu){
                    compCpu = cpu;
                }
                
                for(Componente ram : listaRam){
                    compRam = ram;
                }
                
                for(Componente disco : listaDisco){
                    discos2.add(disco);
                }
                
                for(Componente cpu : listaCpuLocal){
                    compCpuLocal = cpu;
                }
                
                for(Componente ram : listaRamLocal){
                    compRamLocal = ram;
                }
                
                for(Componente disco : listaDiscoLocal){
                    discosLocal.add(disco);
                }
                
                JavaDash janela2 = new JavaDash();
                janela2.setIdMaquina(retornoMaquina.getIdMaquina());
                janela2.setCpu(compCpu);
                janela2.setRam(compRam);
                janela2.setListaDisco(discos2);
                janela2.setCpuLocal(compCpuLocal);                
                janela2.setRamLocal(compRamLocal);
                janela2.setListaDiscoLocal(discosLocal);
                janela2.setLocationRelativeTo(null);
                janela2.setVisible(true);
                janela2.setResizable(false);
                
                SerialMaquina serial = new SerialMaquina();
                serial.setSerialMaquina(retornoMaquina.getSerialMaquina());
                serial.setLocationRelativeTo(null);
                serial.setVisible(true);
                serial.setResizable(false);
                
                this.dispose();
            }
            
        }
    }//GEN-LAST:event_btnCadastrarMaquinaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        Login voltarJanela = new Login();
        voltarJanela.setLocationRelativeTo(null);
        voltarJanela.setVisible(true);
        voltarJanela.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarMaquina;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel loading;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNomeServ;
    private javax.swing.JPasswordField tfSenha;
    // End of variables declaration//GEN-END:variables
}
